### GET request to example server
@baseUrl = https://collectionapp.viskode.dk
@token =

###
### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "username": "VideoUser2",
  "password": "TestPassword123",
  "email": "test@test.com"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "username": "VideoUser2",
  "password": "TestPassword123"
}

### Get all users
GET {{baseUrl}}/api/user
Authorization: Bearer {{token}}

### Get user by ID
GET {{baseUrl}}/api/user/1
Authorization: Bearer {{token}}

### Get collections for user
GET {{baseUrl}}/api/user/13/collection
Authorization: Bearer {{token}}

### Get create collection for user
POST {{baseUrl}}/api/user/13/collection
Authorization: Bearer {{token}}

{
  "name": "TestCollection",
  "description": "TestDescription"
}

### Create book in collection
POST {{baseUrl}}/api/collection/1/book
Authorization: Bearer {{token}}

{
   "title": "Sunrise paints the sky",
   "description": "Sunrise paints the sky, Gentle waves kiss sandy shores, Day awakens slow.",
   "authors": ["D. Tyrell", "R. Monke"],
   "releaseYear": 2023,
   "status": "OWNED",
   "condition": "GOOD"
}

### Create item in collection
POST {{baseUrl}}/api/collection/1/item
Authorization: Bearer {{token}}

{
   "name": "Batman",
   "description": "Play figure of Batman from the 1990s",
   "releaseYear": 1992,
   "status": "OWNED",
   "condition": "GOOD"
   "type": "COLLECTIBLE"
}